### ISSUE TITLE
Hosting is still awesome.zeebe.io

### ISSUE THREAD

**Issue by akeller** [camunda-community-hub/awesome-camunda-platform-8#30]
Move to awesome.camunda.io? Somewhere else? The infrastructure for hosting still points to awesome.zeebe.io.

**Comment by falko** [comment]
How about https://awesome.camunda.io? @xomiamoore FYI

**Comment by xomiamoore** [comment]
I think awesome.camunda.io should work, but I submitted a request with marketing to see what they think and get things rolling. I can take this on.

**Comment by xomiamoore** [comment]
The domain has been updated to awesome.camunda.io, thank you to @jessesimpson36 for helping get this set up so quickly! 🚀
